export const HEART_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  SPENT: 'SPENT',
  RETURNED: 'RETURNED',
  EXPIRED: 'EXPIRED',
});

export const GROUP_STATUS = Object.freeze({
  RECRUITING: 'RECRUITING',
  READY: 'READY',
  START_SCHEDULED: 'START_SCHEDULED',
  ACTIVE: 'ACTIVE',
  RECRUITMENT_FAILED: 'RECRUITMENT_FAILED',
  SETTLEMENT_PENDING: 'SETTLEMENT_PENDING',
  SETTLING: 'SETTLING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const MEMBERSHIP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ACTIVE: 'ACTIVE',
  WITHDRAWN: 'WITHDRAWN',
  COMPLETED: 'COMPLETED',
  SANCTIONED: 'SANCTIONED',
});

export const VERIFICATION_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  ANALYZING: 'ANALYZING',
  PROVISIONALLY_APPROVED: 'PROVISIONALLY_APPROVED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED',
  APPEALED: 'APPEALED',
  OPERATOR_REVIEW: 'OPERATOR_REVIEW',
  FINAL_APPROVED: 'FINAL_APPROVED',
  FINAL_REJECTED: 'FINAL_REJECTED',
});

export const SETTLEMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SETTLING: 'SETTLING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

export const RETRY_MISSION_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REWARDED: 'REWARDED',
  EXPIRED: 'EXPIRED',
  BLOCKED: 'BLOCKED',
});
